import { Document, Page, Text, View, StyleSheet } from 'npm:@react-pdf/renderer@3.4.4'
import * as React from 'npm:react@18.3.1'

interface TransactionData {
  userName: string
  transactionType: string
  amount: string
  reference: string
  date: string
  status: string
  description?: string
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2 solid #10b981',
    paddingBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#10b981',
    marginBottom: 10,
  },
  companyInfo: {
    fontSize: 10,
    color: '#666',
  },
  section: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  label: {
    width: '40%',
    fontWeight: 'bold',
    color: '#333',
  },
  value: {
    width: '60%',
    color: '#666',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 10,
    color: '#999',
    borderTop: '1 solid #e6ebf1',
    paddingTop: 20,
  },
  statusBadge: {
    padding: '5 10',
    borderRadius: 4,
    backgroundColor: '#d1fae5',
    color: '#065f46',
    fontSize: 10,
    fontWeight: 'bold',
  },
})

export const TransactionReceiptPDF = ({
  userName,
  transactionType,
  amount,
  reference,
  date,
  status,
  description,
}: TransactionData) => (
  React.createElement(Document, null,
    React.createElement(Page, { size: 'A4', style: styles.page },
      React.createElement(View, { style: styles.header },
        React.createElement(Text, { style: styles.title }, 'NaijaLancers'),
        React.createElement(Text, { style: styles.companyInfo }, 'Transaction Receipt'),
        React.createElement(Text, { style: styles.companyInfo }, 'CAC Registration: BN8870047'),
        React.createElement(Text, { style: styles.companyInfo }, 'support@naijalancers.com | +234 816 714 0857')
      ),
      
      React.createElement(View, { style: styles.section },
        React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Customer Name:'),
          React.createElement(Text, { style: styles.value }, userName)
        ),
        React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Transaction Type:'),
          React.createElement(Text, { style: styles.value }, transactionType)
        ),
        React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Amount:'),
          React.createElement(Text, { style: styles.value }, amount)
        ),
        React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Reference:'),
          React.createElement(Text, { style: styles.value }, reference)
        ),
        React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Date:'),
          React.createElement(Text, { style: styles.value }, date)
        ),
        React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Status:'),
          React.createElement(Text, { style: styles.statusBadge }, status)
        ),
        description && React.createElement(View, { style: styles.row },
          React.createElement(Text, { style: styles.label }, 'Description:'),
          React.createElement(Text, { style: styles.value }, description)
        )
      ),
      
      React.createElement(View, { style: styles.footer },
        React.createElement(Text, null, 'This is an automated receipt generated by NaijaLancers'),
        React.createElement(Text, null, 'For support, contact us at support@naijalancers.com')
      )
    )
  )
)
